Big restructuring based on docker-compose deployments (#25)
* Dropped coverage role

* Added appleboy and ssh keys

* Fixed root ssh keys

* Big restructuring based on docker-compose deployments

diff --git a/bin/ansible b/bin/ansible
--- a/bin/ansible
+++ b/bin/ansible
@@ -14,5 +14,12 @@ then
     exit 1
 fi
 
+if ! test -f ${ROOT}/.vault
+then
+    echo "Failed to find .vault file!"
+    exit 1
+fi
+
 exec ansible \
-  --inventory-file=${ROOT}/ansible/hosts.ini $@
+    --vault-password-file=${ROOT}/.vault \
+    --inventory-file=${ROOT}/ansible/hosts.ini $@
diff --git a/bin/playbook b/bin/playbook
--- a/bin/playbook
+++ b/bin/playbook
@@ -14,6 +14,13 @@ then
     exit 1
 fi
 
+if ! test -f ${ROOT}/.vault
+then
+    echo "Failed to find .vault file!"
+    exit 1
+fi
+
 exec ansible-playbook \
+    --vault-password-file=${ROOT}/.vault \
     --inventory-file=${ROOT}/ansible/hosts.ini \
     ${ROOT}/ansible/playbook.yml $@
